apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: m324-csbe1
  name: type-test-deployment
  labels:
    app: type-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: type-test
  template:
    metadata:
      labels:
        app: type-test
    spec:
      containers:
        - name: type-test-container
          image: jl115/type-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: type-test # Change this to your app name
  namespace: m324-csbe1 # Ask the teacher for the namespace name
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: type-test # Change this to your app name
