name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development'
    runs-on:
      group: default
    #runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #e
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --passWithNoTests

      - name: Run Build
        run: yarn build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jl115/type-test -f Dockerfile .

      - name: Push Docker image
        run: docker push jl115/type-test

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.0"

      - name: Set kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f .k8s/deployment.yaml

      - name: Deploy Ingress
        run: kubectl apply -f .k8s/ingress.yaml

      - name: Deploy Service
        run: kubectl apply -f .k8s/service.yaml

      - name: Verify Deployment
        run: kubectl rollout status deployment/type-test-deployment
